ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim

ARG PORT
ARG NUM_WORKERS
ARG NUM_THREADS
ARG MAX_REQUESTS
ARG MAX_REQUESTS_JITTER
ARG PRIVATE_ARTIFACT_REPOSITORY="https://pypi.org/simple"

ENV PORT=${PORT:-8080}
ENV NUM_WORKERS=${NUM_WORKERS:-1}
ENV NUM_THREADS=${NUM_THREADS:-1}
ENV MAX_REQUESTS=${MAX_REQUESTS:-100}
ENV MAX_REQUESTS_JITTER=${MAX_REQUESTS_JITTER:-20}

# ENV variable to avoid TIMEOUT error 'pip'
ENV PIP_DEFAULT_TIMEOUT=600

ENV PYTHONUNBUFFERED True
ENV APP_HOME /app

WORKDIR $APP_HOME

RUN echo "PORT=${PORT} NUM_THREADS=${NUM_THREADS} NUM_WORKERS=${NUM_WORKERS} MAX_REQUESTS=${MAX_REQUESTS} MAX_REQUESTS_JITTER=${MAX_REQUESTS_JITTER}"

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --extra-index-url ${PRIVATE_ARTIFACT_REPOSITORY} -r requirements.txt

COPY src/ src/

COPY entrypoint.sh ${APP_HOME}/entrypoint.sh
RUN chmod +x ${APP_HOME}/entrypoint.sh
ENTRYPOINT ${APP_HOME}/entrypoint.sh